WebServicos/webservicos/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webservicos.Models;

namespace webservicos.Controllers
{
    public class FeedbackController : Controller
    {
        //
        // GET: /Feedback/
       
        public ActionResult Index(string pesquisa)
        {
            try
            {
                var lst = new FeedbackDAO().Listar();
                return View(lst);
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao buscar feedbacks. {0}", ex.Message);
                return View(new List<Feedback>());
            }
        }
        [Authorize]
        public ActionResult Cadastro()
        {
            return View();
        }
        [Authorize(Roles =  "Administrador")]
        public ActionResult Editar(int? id)
        {
            if (id == null || id == 0)
                return View();

            try
            {
                var obj = new FeedbackDAO().Buscar((int)id);
                return View(obj);
            }
            catch (KeyNotFoundException ex)
            {
                TempData["ErrorMsg"] = ex.Message;
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Não foi possivel buscar o feedback. {0}", ex.Message);
                return View();
            }
        }
        [Authorize]
        public ActionResult Salvar(Feedback obj)
        {
            if (!ModelState.IsValid)
            {
                return View("Cadastro", obj);
            }

            try
            {
                var usuario = (Usuario)Session["usuario"];

                new FeedbackDAO().Salvar(obj, usuario);

                TempData["SucessMsg"] = "Feedback salvo com sucesso!";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao salvar o feedback. {0}", ex.Message);
            }
            //return View("Editar", obj); 
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Administrador")]
        public ActionResult Excluir(int id)
        {
            try
            {
                var usuario = (Usuario)Session["usuario"];

                new FeedbackDAO().Delete(new Feedback { Codigo = id }, usuario);
                TempData["SucessMsg"] = "Feedback excluído com sucesso.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao excluir feedback. {0}", ex.Message);
            }

            return RedirectToAction("Index");
        }
        public ActionResult Detalhes(int id)
        {
            try
            {
                var obj = new FeedbackDAO().Buscar(id);
                return View(obj);
            }
            catch (KeyNotFoundException ex)
            {
                TempData["ErrorMsg"] = ex.Message;
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Não foi possivel buscar o Feedback. {0}", ex.Message);
                return View();
            }
        }
    }
}

WebServicos/webservicos/Controllers/ServicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webservicos.Models;

namespace webservicos.Controllers
{
    public class ServicoController : Controller
    {
        // GET: Servico
        public ActionResult Index(string pesquisa)
        {
            try
            {
                var lst = new ServicoDAO().Listar();
                return View(lst);
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao buscar serviços. {0}", ex.Message);
                return View(new List<Servico>());
            }
        }

        [Authorize]
        public ActionResult Cadastro()
        {
            var lista = new TipoServicoDAO().Listar();
            ViewBag.TipoServico = lista;

            return View();
        }

        [Authorize]
        public ActionResult Editar(int? id)
        {
            var lista = new TipoServicoDAO().Listar();
            ViewBag.TipoServico = lista;

            if (id == null || id == 0)
                return View();

            try
            {
                var obj = new ServicoDAO().Buscar((int)id);
                return View(obj);
            }
            catch (KeyNotFoundException ex)
            {
                TempData["ErrorMsg"] = ex.Message;
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Não foi possivel buscar o serviço. {0}", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult Salvar(Servico obj)
        {
            var lista = new TipoServicoDAO().Listar();
            ViewBag.TipoServico = lista;

            if (!ModelState.IsValid)
            {
                return View("Cadastro", obj);
            }
            try
            {
                var usuario = (Usuario)Session["usuario"];
                new ServicoDAO().Salvar(obj, usuario);
                TempData["SucessMsg"] = "Servico salvo com sucesso!";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao salvar o serviço. {0}", ex.Message);
            }
            //return View("Editar", obj); 
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Excluir(int id)
        {
            var lista = new TipoServicoDAO().Listar();
            ViewBag.TipoServico = lista;
            try
            {
                var usuario = (Usuario)Session["usuario"];
                new ServicoDAO().Delete(new Servico { Codigo = id }, usuario);
                TempData["SucessMsg"] = "Serviço excluído com sucesso.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao excluir serviço. {0}", ex.Message);
            }

            return RedirectToAction("Index");
        }
        public ActionResult Detalhes(int id)
        {
            try
            {
                var obj = new ServicoDAO().Buscar(id);
                return View(obj);
            }
            catch (KeyNotFoundException ex)
            {
                TempData["ErrorMsg"] = ex.Message;
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Não foi possivel buscar o servico. {0}", ex.Message);
                return View();
            }
        }

        public ActionResult Pesquisar(string pesquisa)
        {
            try
            {
                var lst = new ServicoDAO().Pesquisar(pesquisa);
                return View(lst);
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao buscar serviços. {0}", ex.Message);
                return View(new List<Servico>());
            }
        }
    }
}

WebServicos/webservicos/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WEB SERVIÇOS</title>
    @Styles.Render("~/Content/bootstrap.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Abrir Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <img src="~/Images/webservicos-icon2.png" />

                <a class="navbar-brand" href="@Url.Action("Index", "Home")">WEB SERVIÇOS</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Serviços <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                @{var usuario = (webservicos.Models.Usuario)Session["usuario"];
                                if (usuario != null)
                                {
                                    @Ajax.ActionLink("Novo", "Cadastro", "Servico", null, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "body" }, new { });
                                }}
                        </li>
                        <li>@Html.ActionLink("Visualizar todos", "Index", "Servico")</li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                    @if (usuario == null)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastre-se<span class="caret"></span></a>
                            <ul class="dropdown-menu">

                                <li>@Ajax.ActionLink("Novo cadastro", "Cadastro", "Usuario", null, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "body" }, new { })</li>
                                <li>@Ajax.ActionLink("Login", "Login", "Home", null, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "body" }, new { })</li>

                            </ul>
                        </li>
                }
            </ul>
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Feedback <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Avalie os nossos serviços", "Cadastro", "Feedback")</li>
                        <li>@Html.ActionLink("Avaliações", "Index", "Feedback")</li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" action="@Url.Action("Pesquisar", "Servico")">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Buscar serviço..." name="pesquisa">
                </div>
                <button type="submit" class="btn btn-default">Buscar</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                @if (usuario != null)
            {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            @{
                                var bemvindo = "";
                                //var usuario = (webservicos.Models.Usuario)Session["usuario"];

                                if (usuario != null)
                                {
                                    bemvindo = String.Format("Bem vindo(a) {0}!", usuario.PrimeiroNome);
                                }
                            }

                            @bemvindo
                            
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                         <li>@Ajax.ActionLink("Meu perfil", "Perfil", "Usuario", null, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "body" }, new { })</li>
                            <li>@Ajax.ActionLink("Meus serviços", "Agenda", "Usuario", null, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "body" }, new { })</li>

                                @if (((webservicos.Models.Usuario)Session["Usuario"]).Login == "Administrador")
                                {
                                <li><a href=../Usuario/Index>Visualizar usuários</a></li>
                                }

                            <li role="separator" class="divider"></li>
                            <li>@Ajax.ActionLink("Sair", "Logout", "Home", null, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "body" }, new { })</li>
                        </ul>
                    </li>
                                }
            </ul>
        </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WEB SERVIÇOS - SENAI - Curso Técnico em Informática</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

WebServicos/webservicos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application - Ana Nicole Massaneiro - Carolina Antunes </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WEB SERVIÇOS", "Indice", "Pagina Inicial", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pagina Inicial", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("FeedBack", "FeedBack", "FeedBack")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application - Ana Nicole Massaneiro - Carolina Antunes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebServicos/webservicos/Views/Shared/_LayoutOLD.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application - Ana Nicole Massaneiro - Carolina Antunes </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WEB SERVIÇOS", "Indice", "Pagina Inicial", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pagina Inicial", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("FeedBack", "FeedBack", "FeedBack")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application - Ana Nicole Massaneiro - Carolina Antunes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>